systemd_add_unit proxy.service
systemd_add_unit subscription/proxy-subscription-update.service
systemd_add_unit subscription/proxy-subscription-update.timer
systemd_add_unit proxy-restart.path
systemd_add_unit proxy-restart.service
