#!/usr/bin/env bash

declare -xr IF_NAME=$1
declare -xr TTY_DEVICE=$2
declare -xr SPEED=$3
declare -xr LOCAL_IP=$4
declare -xr REMOTE_IP=$5
declare -xr IP_PARAM=$6

export PATH=/sbin:/usr/sbin:/bin:/usr/bin

logger --tag 'pppoe:ipv6' "[ipv6-up] interface-name=$IF_NAME tty-device=$TTY_DEVICE speed=$SPEED local-link-local-address=$LOCAL_IP remote-link-local-address=$REMOTE_IP ipparam=$IP_PARAM"
env | logger --tag 'pppoe:ipv6'
